import Head from 'next/head'
import Login from '../components/Login'
import UserDashboard from './UserDashboard'
import { useAuth } from '../context/AuthContext'

export default function Home() {

  const { currentUser } = useAuth()

  console.log(currentUser)

  return (
    <>
      <Head>
        <title>CRUD APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {!currentUser && <Login />}
      {currentUser && <UserDashboard />}
    </>
  )
}
